creation_rules:
  - path_regex: ^secrets/default\.ya?ml$
    key_groups:
      - age:
          - age1d9afgcnyv7xv79yywdmeyp62tkgav0kwpjlq0hqvadxzyznx955qpupqhf
          - age1c5nd7dejnmhksjtuy9ddm6l4c5szgr36srdefc2nm3qzjnl20a8sjknvzr
          - age1qrh4wefl5xyl8se62mp2lg970mtrazhes7007ldqlhm2tvkt8d2sys3zgf
          - age1eep4vfce2ha56av0tqfe5srjn3cmextyjkga4kypt0697k9syvgsuc935j
          - age1yv0mg3rfkcz9gfg96dw7e7n0p2s6gm2kx3cw3z2q2hlu89j2vdaqnsx2jv
          - age1qp97mklukfhwux8xr04eplzlnmzenrekx34n6j267t80jwq55s2sear0l8

  - path_regex: ^secrets/systems/day\.ya?ml$
    key_groups:
      - age:
          - age1d9afgcnyv7xv79yywdmeyp62tkgav0kwpjlq0hqvadxzyznx955qpupqhf
          - age1c5nd7dejnmhksjtuy9ddm6l4c5szgr36srdefc2nm3qzjnl20a8sjknvzr

  - path_regex: ^secrets/systems/arbourcloud\.ya?ml$
    key_groups:
      - age:
          - age1d9afgcnyv7xv79yywdmeyp62tkgav0kwpjlq0hqvadxzyznx955qpupqhf
          - age1qrh4wefl5xyl8se62mp2lg970mtrazhes7007ldqlhm2tvkt8d2sys3zgf

  - path_regex: ^secrets/systems/dawn\.ya?ml$
    key_groups:
      - age:
          - age1d9afgcnyv7xv79yywdmeyp62tkgav0kwpjlq0hqvadxzyznx955qpupqhf
          - age1eep4vfce2ha56av0tqfe5srjn3cmextyjkga4kypt0697k9syvgsuc935j

  - path_regex: ^secrets/systems/spring\.ya?ml$
    key_groups:
      - age:
          - age1d9afgcnyv7xv79yywdmeyp62tkgav0kwpjlq0hqvadxzyznx955qpupqhf
          - age1yv0mg3rfkcz9gfg96dw7e7n0p2s6gm2kx3cw3z2q2hlu89j2vdaqnsx2jv

  - path_regex: ^secrets/systems/winter\.ya?ml$
    key_groups:
      - age:
          - age1d9afgcnyv7xv79yywdmeyp62tkgav0kwpjlq0hqvadxzyznx955qpupqhf
          - age1qp97mklukfhwux8xr04eplzlnmzenrekx34n6j267t80jwq55s2sear0l8

  - path_regex: ^secrets/users/adam\.ya?ml$
    key_groups:
      - age:
          - age1d9afgcnyv7xv79yywdmeyp62tkgav0kwpjlq0hqvadxzyznx955qpupqhf
          - age1c5nd7dejnmhksjtuy9ddm6l4c5szgr36srdefc2nm3qzjnl20a8sjknvzr
          - age1qrh4wefl5xyl8se62mp2lg970mtrazhes7007ldqlhm2tvkt8d2sys3zgf
          - age1eep4vfce2ha56av0tqfe5srjn3cmextyjkga4kypt0697k9syvgsuc935j
          - age1yv0mg3rfkcz9gfg96dw7e7n0p2s6gm2kx3cw3z2q2hlu89j2vdaqnsx2jv
          - age1qp97mklukfhwux8xr04eplzlnmzenrekx34n6j267t80jwq55s2sear0l8

  - path_regex: ^secrets/.*\.ya?ml$
    key_groups:
      - age:
          - age1d9afgcnyv7xv79yywdmeyp62tkgav0kwpjlq0hqvadxzyznx955qpupqhf
