passwd: ENC[AES256_GCM,data:dpEu/WBLblb9wMKD1qJQUKTwwMy+HG4kPuKeZ2IiG2ppW2Yc4RWGgC8goKG0NHn+zRa0JDlEuT7J696valPcwB4Q7W24Dq77aA==,iv:mn90sVcG031Ku1ieWw0rVPrq6QCkqialZIwE9yIPsQk=,tag:Ji0IsxyQ3yEyco6RVpns1g==,type:str]
acme_email: ENC[AES256_GCM,data:MzGipdYntKfGQlTbYoh6NY8q3SLLSYAn,iv:6Q4fu5hmL1BloxtK8KWe4WI+QMUiAiWWCTCxsvImNhI=,tag:bnl8p2MdI1GgrqKsArWuJQ==,type:str]
b2_alchemy:
    id: ENC[AES256_GCM,data:RB8adPi2NOkt9mnWPqPl4Wm7ExuxiDGyuw==,iv:OJoQP3UMlfKUW06suG0K/PILeNIkEMBoR9Z/bqQyw+4=,tag:er7cK6uawGBffxRuEsapCQ==,type:str]
    key: ENC[AES256_GCM,data:pj2vL13ZwG1pqmVz4UTBytxtm9yM+3X9+LuL0ud8TA==,iv:AJVRzsHLqNz1lmNNhCFTNXK9uih6NKtQikB2jb+jzGU=,tag:LU0ZgZL3HvoOqZ+U4jtLfQ==,type:str]
sops:
    age:
        - recipient: age1d9afgcnyv7xv79yywdmeyp62tkgav0kwpjlq0hqvadxzyznx955qpupqhf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMHpWcHQreXlpdjBDSC9F
            b0Nnd1hqZlJ1MEx1N3J2MHF6SUovNWwzemxVCjJpZ2FGb0F2NFVxdmZmK3htY1Er
            M29TRmx0M0V3cmloVmdJYTRzcjNUeGMKLS0tIDQzMDhUTmJSbGgrbWZyK0xUcHdN
            WW1JQzl4ZkM4dVJqdUZGSno5OHFnYWcKQq8kUDySGfPYU//cS5YduNI3Aut9UDSg
            JUcOF7JZnMM5HIAJzSdsrk/0pfTLkcsGe09uy5c3cAoiAL1pa2RUHw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y902e6ry8pp9yvkwq8nawzj363my25flj6fjxv6ljcp0emztq50qerkrnp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoOXB5ZjdveDhzeTI1bzgr
            cUs4T2JZSERWNXM3M2hTRFZaQ0c2MHA3TUhJClNrQWpEWGxUVHB5WDlsc21Fa0gy
            UXFhb1FXV05hZHl3c1NzYlVURFNOMnMKLS0tIDVOQXViOVlybUplVTI3Syt4NE10
            THJpNXQ2SjA5ZU0wUld2UjB1RWRCczQKgZ9zWFl0YFpOyLr5reCyFks23B3u3uHT
            LpbxptVlHKCTsk15GaTtlrRWgvJYCFkcWGV0dWorqDqMMFLhE3sYmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T18:30:55Z"
    mac: ENC[AES256_GCM,data:tbx0dX3+6bFzlW4Rri9ju13T60MSDt2C+0bAeF6Y8B+m6SeZzOR6Fpam0ux1Oz7Ye7b+Vfh8agmQa71F42F3RJX9vVO0GFn3xgRJBesTn5oZCrR+Y1rVr/3WEDUoLGkksu4geb74T+y3+MfvLACP4EIdGBcOI8O44AqvKtwyoSY=,iv:xcSSctGQa8pnoRyYIZkDxJT+ZatvSafUrL404SsZIHg=,tag:6d+GvcomD4f2vpuCurp96A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
