passwd: ENC[AES256_GCM,data:dpEu/WBLblb9wMKD1qJQUKTwwMy+HG4kPuKeZ2IiG2ppW2Yc4RWGgC8goKG0NHn+zRa0JDlEuT7J696valPcwB4Q7W24Dq77aA==,iv:mn90sVcG031Ku1ieWw0rVPrq6QCkqialZIwE9yIPsQk=,tag:Ji0IsxyQ3yEyco6RVpns1g==,type:str]
acme_email: ENC[AES256_GCM,data:Y+SDAmqnRF2FMytxO4jCO5+tdvfs,iv:Mj9QmSN8lsaSzhj70loWaem5ocTm9XEaIUwEJ/fk034=,tag:OyUsBCNbi8u/rEW3hD0cTQ==,type:str]
sops:
    age:
        - recipient: age1d9afgcnyv7xv79yywdmeyp62tkgav0kwpjlq0hqvadxzyznx955qpupqhf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMHpWcHQreXlpdjBDSC9F
            b0Nnd1hqZlJ1MEx1N3J2MHF6SUovNWwzemxVCjJpZ2FGb0F2NFVxdmZmK3htY1Er
            M29TRmx0M0V3cmloVmdJYTRzcjNUeGMKLS0tIDQzMDhUTmJSbGgrbWZyK0xUcHdN
            WW1JQzl4ZkM4dVJqdUZGSno5OHFnYWcKQq8kUDySGfPYU//cS5YduNI3Aut9UDSg
            JUcOF7JZnMM5HIAJzSdsrk/0pfTLkcsGe09uy5c3cAoiAL1pa2RUHw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y902e6ry8pp9yvkwq8nawzj363my25flj6fjxv6ljcp0emztq50qerkrnp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoOXB5ZjdveDhzeTI1bzgr
            cUs4T2JZSERWNXM3M2hTRFZaQ0c2MHA3TUhJClNrQWpEWGxUVHB5WDlsc21Fa0gy
            UXFhb1FXV05hZHl3c1NzYlVURFNOMnMKLS0tIDVOQXViOVlybUplVTI3Syt4NE10
            THJpNXQ2SjA5ZU0wUld2UjB1RWRCczQKgZ9zWFl0YFpOyLr5reCyFks23B3u3uHT
            LpbxptVlHKCTsk15GaTtlrRWgvJYCFkcWGV0dWorqDqMMFLhE3sYmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T14:27:52Z"
    mac: ENC[AES256_GCM,data:Tyc586+FGLOCMu0K1aHaNlR04X7wyWNayVF/hHAYCzuXhrrAng6srkNx1XUMJdst0o94wgbL3atVLFhyR8hz6v2+j+5TtMw9xqeS+V03VGvJo5o6lrHoZKVdFEU3njDMMVc33KjRHiHl8kUljnkVnJsDGkre3I8Otp8zzpDMg7U=,iv:RfEOny6yjT331F985f117t9GgCsA+jXUNscvSA+KPHg=,tag:j3m4JrD/C/RXdioUvGVFvw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
