passwd: ENC[AES256_GCM,data:dpEu/WBLblb9wMKD1qJQUKTwwMy+HG4kPuKeZ2IiG2ppW2Yc4RWGgC8goKG0NHn+zRa0JDlEuT7J696valPcwB4Q7W24Dq77aA==,iv:mn90sVcG031Ku1ieWw0rVPrq6QCkqialZIwE9yIPsQk=,tag:Ji0IsxyQ3yEyco6RVpns1g==,type:str]
sops:
  age:
    - recipient: age1d9afgcnyv7xv79yywdmeyp62tkgav0kwpjlq0hqvadxzyznx955qpupqhf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMHpWcHQreXlpdjBDSC9F
        b0Nnd1hqZlJ1MEx1N3J2MHF6SUovNWwzemxVCjJpZ2FGb0F2NFVxdmZmK3htY1Er
        M29TRmx0M0V3cmloVmdJYTRzcjNUeGMKLS0tIDQzMDhUTmJSbGgrbWZyK0xUcHdN
        WW1JQzl4ZkM4dVJqdUZGSno5OHFnYWcKQq8kUDySGfPYU//cS5YduNI3Aut9UDSg
        JUcOF7JZnMM5HIAJzSdsrk/0pfTLkcsGe09uy5c3cAoiAL1pa2RUHw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1y902e6ry8pp9yvkwq8nawzj363my25flj6fjxv6ljcp0emztq50qerkrnp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoOXB5ZjdveDhzeTI1bzgr
        cUs4T2JZSERWNXM3M2hTRFZaQ0c2MHA3TUhJClNrQWpEWGxUVHB5WDlsc21Fa0gy
        UXFhb1FXV05hZHl3c1NzYlVURFNOMnMKLS0tIDVOQXViOVlybUplVTI3Syt4NE10
        THJpNXQ2SjA5ZU0wUld2UjB1RWRCczQKgZ9zWFl0YFpOyLr5reCyFks23B3u3uHT
        LpbxptVlHKCTsk15GaTtlrRWgvJYCFkcWGV0dWorqDqMMFLhE3sYmw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-01T04:13:50Z"
  mac: ENC[AES256_GCM,data:BtFA+VC6iTFuEiNsmT2bu/bCOArZAh+HM9/8q/DG6r77mH76F0YX1W3pO8jGvGrRT0L7dAWpSldn9EdaP33fpalXZ2ICuLKPCy9eJRTAMhg1PEtF5s3OOX5hk45Q/2xHzoNLR1bSAh+0vRzg5u38rdFgkI5NFjvoCw/bhIC3bsE=,iv:+VRyZOVCtZitYIy0khKVgkerrogqW9if0DbMR13Tp20=,tag:RSLidrxmDaYM0ougPoOLjg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
